spring.application.name=vuelos

spring.datasource.url=jdbc:postgresql://localhost:5432/Examen
spring.datasource.username=postgres
spring.datasource.password=BeckerC2005
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
